Initial version of package
JuliaSystems/IdentificationToolbox.jl pull request #1
Opened 2016-09-27 22:25 UTC by neveritt

2016-09-28 07:19 UTC, aytekinar requested changes
Well, if you don't address the `inline` comments, it will not build anyways --- that's why I have _requested_ changes. Otherwise, I did not check the code itself, but seems neat.

Some notes:
1.  I am not sure if you will squash everything before the first tag, but if not, please change the `stupid stuff` commit message, at least ;)
2.  Later on, I will also try to change the code in `ControlCore`, for example, to use the Unicode (i.e., actual Greek) letters of `alpha`, `beta`, etc. Maybe you can find and replace these `lambda`s with `\lambda`s. This is just a minor thing, obviously :)

2016-09-28 07:19 UTC, aytekinar commented on src/.travis.yml
> +  - julia --check-bounds=yes --inline=no -e 'Pkg.test("{[{package}]}",
You have forgot to change the `{[{package}]}` placeholder.

2016-09-28 07:19 UTC, aytekinar commented on src/.travis.yml
> +  - julia -e 'cd(Pkg.dir("{[{package}]}")); Pkg.add("Coverage"); using Coverage;
`{[{package}]}` place holder.

Well, if you enable CI through Travis for this repo, you will notice this yourself. Maybe it's better to just enable it and see how the build goes.

2016-09-28 07:19 UTC, aytekinar commented on src/.travis.yml
> +    Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
we need to put a *new line*, here, apparently.

2016-09-29 06:43 UTC, neveritt commented on src/.travis.yml
> +  - julia -e 'cd(Pkg.dir("{[{package}]}")); Pkg.add("Coverage"); using Coverage;
good thinking.

2016-09-29 06:43 UTC, neveritt commented on src/.travis.yml
> +    Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
apparently

2016-10-18 15:51 UTC, aytekinar approved these changes

2016-10-18 15:52 UTC, merged